### ISSUE TITLE
[FEATURE] - Browser Source

### ISSUE THREAD

**Issue by Margino** [FiniteSingularity/obs-quick-access-utility#57]
If possible, please add the ability to interact with the "Browser Source"
<img width="505" alt="screen" src="https://github.com/user-attachments/assets/19d5b4df-44ac-4957-8991-cedb55fe6f7d">

Thanks for your great work!

**Comment by FiniteSingularity** [comment]
Thank you for the feature request.

I think this should be doable.  There is a call in the frontend API for "Open source interaction window", which I am pretty sure would be the browser interact: https://docs.obsproject.com/reference-frontend-api#c.obs_frontend_open_source_interaction

I'd also potentially like to get the refresh button to work as well, however this one doesnt seem as clear.

In order to keep the docks clean, I'm thinking this would be best as a right-click/Context menu option, rather than a new button in the dock (as it is specific to one particular source type).  Does that sound like it would meet your needs?

**Comment by Margino** [comment]
Sounds great! 

I use the plugin to safely use OBS to prevent accidental clicks on "dangerous" buttons. And in my case the refresh button is potentially dangerous. For example, it can destroy all progress if a timer is running in the browser. So I'd vote for not adding the refresh button or at least separating it from the others (anyway, the refresh button is available in the Properties tab).

Anyway, I'll be glad to see any implementation.
